# Copyright 2022 DARWIN EU (C)
#
# This file is part of DrugUtilisation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' This function is used to summarise the dose table over multiple cohorts.
#'
#' @param cohort Cohort with drug use variables and strata
#' @param cdm cdm_reference generated by CDMConnector
#' @param strata Stratification list
#' @param drugUseVariables Name of columns with drug use variables
#' @param drugUseEstimates Estimates that we want for the columns
#' @param minCellCount Below this number counts will be supressed
#'
#' @return A summary of the drug use stratified by cohort_name and strata_name
#'
#' @export
#'
#' @examples
#' \donttest{
#' library(DrugUtilisation)
#' library(PatientProfiles)
#' library(CodelistGenerator)
#'
#' concept_relationship <- dplyr::tibble(
#' concept_id_1 = c(2905077, 1516983, 2905075, 1503327, 1516978, 1503326, 1503328, 1516980,
#'                  29050773, 1125360, 15033297, 15030327, 15033427, 15036327, 15394662,
#'                  43135274, 11253605, 431352774, 431359274, 112530, 1539465, 29050772,
#'                  431352074, 15394062, 43135277, 15033327, 11253603, 15516980, 5034327,
#'                  1539462, 15033528, 15394636, 15176980, 1539463, 431395274, 15186980,
#'                  15316978),
#' concept_id_2 = c(19016586, 46275062, 35894935, 19135843, 19082107, 19011932, 19082108,
#'                  2008660,  2008661,  2008662, 19082109, 43126087, 19130307, 42629089,
#'                  19103220, 19082048, 19082049, 19082256, 19082050, 19082071, 19082072,
#'                  19135438, 19135446, 19135439, 19135440, 46234466, 19082653, 19057400,
#'                  19082227, 19082286, 19009068, 19082628, 19082224, 19095972, 19095973,
#'                  35604394, 702776 ),
#' relationship_id = c(rep("RxNorm has dose form", 37))
#' )
#' cdm <- mockDrugUtilisation(extraTables = list("concept_relationship" = concept_relationship))
#' cdm <- generateDrugUtilisationCohortSet(
#'   cdm, "dus_cohort", getDrugIngredientCodes(cdm, "acetaminophen")
#' )
#' cdm$dus_cohort <- cdm$dus_cohort %>%
#'   addDrugUse(cdm, 1125315)
#' result <- summariseDrugUse(cdm$dus_cohort, cdm)
#' print(result)
#'
#' cdm$dus_cohort <- cdm$dus_cohort %>%
#'   addSex(cdm) %>%
#'   addAge(cdm, ageGroup = list("<40" = c(0, 30), ">40" = c(40, 150)))
#' result <- summariseDrugUse(
#'   cdm$dus_cohort, cdm, strata = list(
#'    "age_group" = "age_group", "sex" = "sex",
#'    "age_group and sex" = c("age_group", "sex")
#'   )
#' )
#' print(result)
#' }
#'
summariseDrugUse<- function(cohort,
                            cdm,
                            strata = list(),
                            drugUseVariables = drugUseColumns(cohort),
                            drugUseEstimates = c("median", "q25", "q75"),
                            minCellCount = 5) {
  # check inputs
  checkInputs(
    cohort = cohort, cdm = cdm, strata = strata,
    drugUseVariables = drugUseVariables, drugUseEstimates = drugUseEstimates,
    minCellCount = minCellCount
  )

  # update cohort_names
  cohort <- cohort %>%
    dplyr::left_join(
      CDMConnector::cohortSet(cohort), by = "cohort_definition_id", copy = TRUE
    )

  # summarise drug use columns
  result <- PatientProfiles::summariseResult(
    table = cohort, group = list("cohort_name" = "cohort_name"),
    strata = strata, variables = list(numericVariables = drugUseVariables),
    functions = list(numericVariables = drugUseEstimates),
    minCellCount = minCellCount
  ) %>%
    dplyr::mutate(
      cdm_name = dplyr::coalesce(CDMConnector::cdmName(cdm), as.character(NA)),
      result_type = "Summary drug use"
    )

  return(result)
}

#' Obtain automatically the drug use columns
#'
#' @param cohort A cohort
#'
#' @return Name of the drug use columns
#'
#' @export
#'
#' @examples
#' \donttest{
#' library(DrugUtilisation)
#' library(CodelistGenerator)
#'
#' concept_relationship <- dplyr::tibble(
#' concept_id_1 = c(2905077, 1516983, 2905075, 1503327, 1516978, 1503326, 1503328, 1516980,
#'                  29050773, 1125360, 15033297, 15030327, 15033427, 15036327, 15394662,
#'                  43135274, 11253605, 431352774, 431359274, 112530, 1539465, 29050772,
#'                  431352074, 15394062, 43135277, 15033327, 11253603, 15516980, 5034327,
#'                  1539462, 15033528, 15394636, 15176980, 1539463, 431395274, 15186980,
#'                  15316978),
#' concept_id_2 = c(19016586, 46275062, 35894935, 19135843, 19082107, 19011932, 19082108,
#'                  2008660,  2008661,  2008662, 19082109, 43126087, 19130307, 42629089,
#'                  19103220, 19082048, 19082049, 19082256, 19082050, 19082071, 19082072,
#'                  19135438, 19135446, 19135439, 19135440, 46234466, 19082653, 19057400,
#'                  19082227, 19082286, 19009068, 19082628, 19082224, 19095972, 19095973,
#'                  35604394, 702776 ),
#' relationship_id = c(rep("RxNorm has dose form", 37))
#' )
#' cdm <- mockDrugUtilisation(extraTables = list("concept_relationship" = concept_relationship))
#' acetaminophen <- getDrugIngredientCodes(cdm, "acetaminophen")
#' cdm <- generateDrugUtilisationCohortSet(
#'   cdm, "dus", acetaminophen
#' )
#' cdm$dus <- cdm$dus %>%
#'   addDrugUse(cdm, 1125315, acetaminophen)
#' drugUseColumns(cdm$dus)
#' }
#'
drugUseColumns <- function(cohort) {
  checkInputs(cohort = cohort)
  names <- colnames(cohort) [colnames(cohort) %in% c(
    "initial_daily_dose", "number_exposures", "duration", "cumulative_dose",
    "number_eras", "initial_quantity", "cumulative_quantity"
  )]
  return(names)
}
